### ISSUE TITLE
Training scripts

### ISSUE THREAD

**Issue by mttgdd** [ramdrop/stun#1]
Hi there, do you have any plans to release training scripts?

**Comment by ramdrop** [comment]
Hi, the training scripts will not be released in the near future as they contain the source code of my unpublished work.

**Comment by mttgdd** [comment]
Ah I'm sorry I didn't realise the paper was unpublished.

**Comment by ramdrop** [comment]
Ah no..  STUN has been accepted by the IROS2022. I mean the training code of STUN contains the code of my other unpublished work.

**Comment by wpumain** [comment]
Stun is a great work.Now I have read the source code you shared and have benefited a lot. Thank you for sharing.
When can you publish your training code?

**Comment by ramdrop** [comment]
The training scripts have now been added.
