### ISSUE TITLE
What are the abbreviations of  nontrivial_positives  ？

### ISSUE THREAD

**Issue by wpumain** [ramdrop/stun#4]
`nontrivial_positives `  is abbreviated from `positives` and which other words?

**Comment by wpumain** [comment]
https://github.com/ramdrop/stun/blob/d4fd9b0fe8f34a6f5c6a797c80467b0c72c7e88f/trainer.py#L501
`whole_mu`  is abbreviated from `whole` and which other words?

**Comment by ramdrop** [comment]
What do you mean?

**Comment by wpumain** [comment]
Thank you for your guidance. I have now resolved the issue.
