### ISSUE TITLE
A question about piits.py

### ISSUE THREAD

**Issue by shenyehui** [ramdrop/stun#6]
Thank you for your great work! But I have a question about your pitts.py code. Since self.cache = None in line 253, is there no file open in line 270 with h5py.File(self.cache, mode='r') as h5, then the meaning of the code with h5py.File(self.cache, mode='r') as h5 is What?

**Comment by ramdrop** [comment]
Thanks for your interest.

It is mandatory that embeddings cache be built at the start of training epoch. This ensures that self.cache is **not** None whenever the `__get_item()__` is being executed.

**Comment by shenyehui** [comment]
Although embedding cache is built at the beginning of training epoch，In class QueryDatasetFromStruct(data.Dataset):
    def __init__(）...，define self.cache = None，Won't self.cache become none due to this command。
（您好，我还是没能明白，虽然在epoch开始前定义了self.cache的路径，但是在class QueryDatasetFromStruct(data.Dataset)的初始化里面定义了self.cache=none,然后才执行with h5py.File(self.cache, mode='r') as h5,这样不会覆盖前面的命令使得self.cache=none吗？）

**Comment by ramdrop** [comment]
The execution flow is:
1. QueryDatasetFromStruct.`init()`: self.cache=None
2. Building embeddings: self.cache=[file_path]
3. QueryDatasetFromStruct.`__get_item()__`: read from self.cache
4. repeat 2 and 3

**Comment by shenyehui** [comment]
Thank you for your patience in answering
